name: Build Basic Docker

on:
  push:
    paths:
      - 'docker/Dockerfilebasic'

jobs:
  call-template:
    uses: ./.github/workflows/build-and-push.yml@main
    with:
      dockerfile: docker/Dockerfilebasic
      full_image: quay.io/mguzman98/shiftleft:v1.0.0
