name: Build Basic Docker

on:
  push:
    paths:
      - 'docker/Dockerfile_basic'

jobs:
  call-template:
    uses: ./.github/workflows/templates/build-and-push.yml
    with:
      dockerfile: docker/Dockerfile_basic
      full_image: quay.io/mguzman98/shiftleft:v1.0.0
