name: Build JBoss Docker

on:
  push:
    paths:
      - 'docker/Dockerfile_jboss_lab'

jobs:
  call-template:
    uses: ./.github/workflows/build_and_push.yml
    secrets: inherit
    with:
      dockerfile: docker/Dockerfile_jboss_lab
      full_image: quay.io/mguzman98/jboss_lab:v1.0.0
