name: Build Basic Docker

on:
  push:
    paths:
      - 'docker/Dockerfilebasic'

jobs:
  call-template:
    uses: ./.github/workflows/build_and_push.yml
    secrets: inherit
    with:
      dockerfile: docker/Dockerfilebasic
      full_image: quay.io/mguzman98/shiftleft_lab:v1.0.0
