name: Build Vulnerable Docker

on:
  push:
    paths:
      - 'docker/Dockerfilevulnerable'

jobs:
  call-template:
    uses: ./.github/workflows/build_and_push.yml
    secrets: inherit
    with:
      dockerfile: docker/Dockerfilevulnerable
      full_image: quay.io/mguzman98/shiftleft_lab:v1.0.0
